# Generated by Django 3.2.18 on 2023-04-30 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_gallerycategory_images'),
        ('user_profile', '0003_auto_20230428_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Shipped'), (3, 'Delivered')], default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.shop')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='user_profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='profile_orders', to='user_profile.Order'),
        ),
    ]
