# Generated by Django 3.2.18 on 2023-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_bio'),
    ]

    operations = [
        # ...
        # Removed the migrations.RemoveField operation for birth_date
        # ...
    ]
